### ISSUE TITLE
Configure existing repositories for use with the planning project

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/000-planning#1]
## Description

- Configure the following repositories with standardized labels, issue templates, milestones, and/or releases
  - Personal website
  - Copy Better
  - Course grapher

## Tasks

- [x] Set up labels in website repo
- [x] https://github.com/wllmwu/wllmwu.github.io/issues/2
- [x] Set up labels in Copy Better repo
- [x] https://github.com/wllmwu/2018-copy-better/issues/30
- [x] Set up next milestone in Copy Better repo
- [x] Refactor issues in Copy Better repo
- ~~_Consider:_ Set up releases in Copy Better repo~~ [Do for future releases]
- [x] Set up labels in course grapher repo
- [x] https://github.com/wllmwu/course-grapher/issues/1
- [x] _Consider:_ Set up next milestone in course grapher repo
